# Assignment Day 25 | 10th August 2020

#### Junior Peña

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
dfdata = df.drop(['PassengerId', 'Cabin', 'Ticket', 'Name'], axis = 1)
dfdata.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [4]:
le = LabelEncoder()
dfdata['Sex'] = le.fit_transform(dfdata['Sex'])
dfdata['Embarked'] = le.fit_transform(dfdata['Embarked'])

In [5]:
def Naive_Bayes(nb):
    y = dfdata[nb]
    X = dfdata.drop([nb], axis = 1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)
    clf = BernoulliNB()
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    print("The accuracy of the model for predicting ",nb," is", accuracy_score(y_test, y_pred))
    print('\nThe confusion matrix is:\n', confusion_matrix(y_test, y_pred))

## Pclass

In [6]:
Naive_Bayes('Pclass')

The accuracy of the model for predicting  Pclass  is 0.6629213483146067

The confusion matrix is:
 [[21  5 20]
 [ 4  5 22]
 [ 6  3 92]]


## SibSp

In [7]:
Naive_Bayes('SibSp')

The accuracy of the model for predicting  SibSp  is 0.651685393258427

The confusion matrix is:
 [[103  10   0   0   0   0   0]
 [ 39  13   0   0   0   0   0]
 [  1   1   0   0   0   0   0]
 [  2   2   0   0   0   0   0]
 [  3   1   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0]]


## Sex

In [8]:
Naive_Bayes('Sex')

The accuracy of the model for predicting  Sex  is 0.7921348314606742

The confusion matrix is:
 [[ 41  13]
 [ 24 100]]


## Parch 

In [9]:
Naive_Bayes('Parch')

The accuracy of the model for predicting  Parch  is 0.7247191011235955

The confusion matrix is:
 [[124  12   0   0]
 [ 19   5   0   0]
 [ 16   1   0   0]
 [  1   0   0   0]]


## Embarked

In [10]:
Naive_Bayes('Embarked')

The accuracy of the model for predicting  Embarked  is 0.6629213483146067

The confusion matrix is:
 [[  0   0  39]
 [  0   0  21]
 [  0   0 118]]
