# Assignment Day 14 & 15 | 24th July 2020

#### Junior Peña

In [1]:
#Import libraries
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
a = np.random.rand(3,3,3)
print(a)

[[[0.90320974 0.38371332 0.33924135]
  [0.70753302 0.73747137 0.01746201]
  [0.58467118 0.57866137 0.07380623]]

 [[0.45515431 0.06283312 0.07357532]
  [0.4117175  0.92880671 0.32374017]
  [0.38160111 0.67042919 0.41644883]]

 [[0.71860171 0.8260385  0.3843137 ]
  [0.49644739 0.2733792  0.3454266 ]
  [0.97616714 0.25670307 0.83798489]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a = np.diag([1,2,3,4], k = -1)
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
a = np.random.random((5,5))
print("The original array is: \n", a)

amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("\nThe array normalized is: \n", a)

The original array is: 
 [[0.61834259 0.17805917 0.6261752  0.9763974  0.11963569]
 [0.18779035 0.42467312 0.14366649 0.10266315 0.96065028]
 [0.04317191 0.69804952 0.77140539 0.77817981 0.06491212]
 [0.95821192 0.28384415 0.78613175 0.15358104 0.10476669]
 [0.21241088 0.79099013 0.64555591 0.56764459 0.03953897]]

The array normalized is: 
 [[0.61781332 0.14785607 0.62617383 1.         0.08549502]
 [0.1582431  0.41109108 0.11114541 0.06737857 0.98319156]
 [0.00387779 0.70289227 0.78119211 0.78842311 0.02708323]
 [0.98058886 0.26077065 0.79691099 0.12172818 0.06962389]
 [0.18452299 0.80209681 0.64686074 0.56369843 0.        ]]


# 5.  How to find common values between two arrays?

In [6]:
a= list(map(int,input("Please enter the first array: ").split()))
a = np.asarray(a)
print("The first array is: \n",a)

b= list(map(int,input("\nPlease enter the second array: ").split()))
b = np.asarray(b)
print("The second array is: \n",b)

print("\nThe common values between the two arrays are: ")
print(np.intersect1d(a, b))

Please enter the first array: 5 11 18 31 38 45 83 98 112 148
The first array is: 
 [  5  11  18  31  38  45  83  98 112 148]

Please enter the second array: 2 11 31 42 65 83 92 98 105 148
The second array is: 
 [  2  11  31  42  65  83  92  98 105 148]

The common values between the two arrays are: 
[ 11  31  83  98 148]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
a = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's date is: ",a)
b = np.datetime64('today', 'D')
print("Today's date is: ",b)
c = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is: ",c)

Yestraday's date is:  2020-07-26
Today's date is:  2020-07-27
Tomorrow's date is:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
a = np.random.randint(0,2,7)
print("The first array is: ", a)
b = np.random.randint(0,2,7)
print("The second array is: ", b)

equal = np.allclose(a,b)
print("\n¿Are both arrays equal?\n", equal)

The first array is:  [1 1 0 0 1 0 1]
The second array is:  [0 0 1 1 1 1 1]

¿Are both arrays equal?
 False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
a = np.random.random(10)
print("The vector is: ", a)
print("\nThe maximum value is: ", a.max())
a[a.argmax()] = 0
print("\nThe vector after max value being replaced is: ", a)

The vector is:  [0.68505075 0.11078064 0.87429027 0.48006922 0.40279603 0.36312166
 0.10331411 0.17427361 0.33131232 0.35673202]

The maximum value is:  0.874290268283544

The vector after max value being replaced is:  [0.68505075 0.11078064 0.         0.48006922 0.40279603 0.36312166
 0.10331411 0.17427361 0.33131232 0.35673202]


# 9. How to print all the values of an array?

In [10]:
np.set_printoptions(threshold=np.inf)
a = np.zeros((10, 10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [11]:
a = np.random.rand(4, 3)
print("The original array is: \n",a)

b = a - a.mean(axis=1, keepdims=True)
print("\nThe array after the subtraction is: ",b)

The original array is: 
 [[0.60532822 0.40087286 0.0570457 ]
 [0.32625819 0.81367428 0.52880391]
 [0.98333551 0.701188   0.36131841]
 [0.80349488 0.35527742 0.75038457]]

The array after the subtraction is:  [[ 0.25091262  0.04645726 -0.29736989]
 [-0.22998728  0.25742882 -0.02744155]
 [ 0.3013882   0.01924069 -0.3206289 ]
 [ 0.16710926 -0.28110821  0.11399895]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
a = np.ones(10)
print("The first vector is: ", a)
b = np.random.randint(0,len(a),20)
print("The second vector is: ",b)
a += np.bincount(b, minlength=len(a))
print("Thi final vector is: ",a)

The first vector is:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The second vector is:  [1 4 0 9 0 6 8 1 3 0 7 1 8 4 1 2 9 0 7 3]
Thi final vector is:  [5. 5. 2. 3. 3. 1. 2. 3. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [13]:
a = np.random.randint(0,20,(5,5))
print("The first array is: \n",a)
b = np.random.randint(0,20,(5,5))
print("\nThe second array is: \n",b)

c = np.diag(np.dot(a, b))
print("\nThe diagonal of the dot product is: ", c)

The first array is: 
 [[10 16  3 10  7]
 [ 8  3  5 13 16]
 [ 5 11 15 17  4]
 [ 7  7 14 14 13]
 [ 8  4 12  1 15]]

The second array is: 
 [[ 7 12 19  2  0]
 [16 12 17 17 18]
 [ 7 18  3  6  1]
 [13 11  5 11 17]
 [ 0 16 19 12 16]]

The diagonal of the dot product is:  [477 621 488 527 341]


# 13.How to find the most frequent value in an array?

In [14]:
a = np.random.randint(0,50,100)
print("The array is: \n",a)
print("The most frequent value is: ", np.bincount(a).argmax())

The array is: 
 [44 13 39 19  5 21 18 28 11 31 11 43 29 49  3 38 46 46  9 23  2 24 20 21
 43  1 39  7 38 31  6  3 14 12 37 24 17 21  8  3 21 48 17 32 17 27 31 36
 41 44 27 38  4  8 42 17 15  0 41 37  1 14 15 46 43  6 38 38  5 38 43  5
 17  9 12 21 20 39 26 26 48 12 44 48 15 11  7 41 18 48  5 37 11 34 47 38
 31  5  7 35]
The most frequent value is:  38


# 14.How to get the n largest values of an array

In [15]:
a = np.arange(200)
print("The array is: \n",a)
np.random.shuffle(a)
n = 8

print("\nThe ",n," largest values of the array are: ",a[np.argsort(a)[-n:]])

The array is: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]

The  8  largest values of the array are:  [192 193 194 195 196 197 198 199]


# 15.How to create a record array from a regular array?

In [16]:
a = np.array(['Harry','Ronald','Hermione','Luna'])
b = np.array(['James','Bilius','Jean','Lovegood'])
c = np.array(['Potter','Weasley','Granger','Scamander'])
d = np.core.records.fromarrays([a, b, c])
print(d[0])
print(d[1])
print(d[2])
print(d[3])

('Harry', 'James', 'Potter')
('Ronald', 'Bilius', 'Weasley')
('Hermione', 'Jean', 'Granger')
('Luna', 'Lovegood', 'Scamander')
